deployment:
  name: nodejsdbapp
  replicas: 2
  image:
    repository: dheeraj394/node-mongo-db
    tag: "03"
    pullPolicy: IfNotPresent
  containerPort: 3000
  env:
    mongoHost:
      configMapName: mongo-config
      key: MONGO_HOST
    mongoPort:
      configMapName: mongo-config
      key: MONGO_PORT
    mongoDb:
      configMapName: mongo-config
      key: MONGO_DB
    appPort: "3000"
  labels:
    app: nodejsdbapp

service:
  name: nodejsdbapp
  type: LoadBalancer
  loadBalancerIP: 10.10.37.249
  port: 3002
  targetPort: 3000
  protocol: TCP
  selector:
    app: nodejsdbapp
configmap:
  name: mongo-config
  labels:
    app: nodejsdbapp
  data:
    MONGO_HOST: "mongodb.mongodb"
    MONGO_PORT: "27017"
    MONGO_DB: "mydb"

storageClass:
  enabled: true
  name: local-path-immediate
  provisioner: rancher.io/local-path
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

statefulset:
  name: mongodb
  replicas: 2
  serviceName: mongodb
  image:
    repository: mongo
    containerPort: 27017
  volume:
    name: mongo-data
    mountPath: /data/db
    accessModes: ["ReadWriteOnce"]
    storageClassName: local-path-immediate
    size: 1Gi
  labels:
    app: mongodb
    
mongoService:
  name: mongodb
  labels:
    app: mongodb
  clusterIP: None
  port: 27017
  targetPort: 27017
  selector:
    app: mongodb

namespace:
  enabled: true
  name: nodejs-mongodb-app
