apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejsdbapp
  namespace: argocd  # Namespace where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/kumardheeraj394/dheeraj-helm-repository.git
    targetRevision: HEAD
    path: .                        # Adjust this if your chart is in a subdirectory
    helm:
      releaseName: nodejsdbapp     # This is key: sets Helm release name
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nodejsdbapp

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - Replace=true
