apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.configmap.labels.app }}
data:
  MONGO_HOST: "{{ .Values.configmap.data.MONGO_HOST }}"
  MONGO_PORT: "{{ .Values.configmap.data.MONGO_PORT }}"
  MONGO_DB: "{{ .Values.configmap.data.MONGO_DB }}"
