apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.statefulset.name }}
  labels:
    app: {{ .Values.statefulset.labels.app }}
spec:
  serviceName: "{{ .Values.statefulset.serviceName }}"
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.statefulset.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.statefulset.labels.app }}
    spec:
      containers:
        - name: {{ .Values.statefulset.name }}
          image: {{ .Values.statefulset.image.repository }}
          ports:
            - containerPort: {{ .Values.statefulset.image.containerPort }}
          volumeMounts:
            - name: {{ .Values.statefulset.volume.name }}
              mountPath: {{ .Values.statefulset.volume.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.statefulset.volume.name }}
      spec:
        accessModes: {{ toJson .Values.statefulset.volume.accessModes }}
        storageClassName: {{ .Values.statefulset.volume.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.statefulset.volume.size }}
